version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      
  build:
    commands:
      - echo "Setting up GitHub Actions self-hosted runner"
      - echo "The actual build will be handled by GitHub Actions"

artifacts:
  files:
    - '**/*'