name: aws-cb-build-microservices
on:
 push:
   branches:
     - main

jobs:
  scaffold:
    runs-on: 
      - codebuild-ms-dev-${{ github.run_id }}-${{ github.run_attempt }}
    timeout-minutes: 30 
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Verify Docker
        run: |
              docker --version
              docker info
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::680871074040:role/my-github-actions-role
          aws-region: ap-southeast-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: install & setup skaffold
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
           curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
           sudo install skaffold /usr/local/bin/
           skaffold config set default-repo ${REGISTRY}/microservices-demo
           skaffold build --push



    